// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJuPNsxpi7ikoGLQn5L20_am8AQmeLKE',
    appId: '1:701125455472:web:42202eaa929eea1df10eb5',
    messagingSenderId: '701125455472',
    projectId: 'dynamic-5a626',
    authDomain: 'dynamic-5a626.firebaseapp.com',
    storageBucket: 'dynamic-5a626.appspot.com',
    measurementId: 'G-R0519RKEL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysM8m8jQYFgz4UXu_AaUBq4McT8PV9Eg',
    appId: '1:701125455472:android:fc8860fe425690d2f10eb5',
    messagingSenderId: '701125455472',
    projectId: 'dynamic-5a626',
    storageBucket: 'dynamic-5a626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6mhroqAcSc_ihGWtnAuOXHOi9KQXf4s',
    appId: '1:701125455472:ios:abc4687648313945f10eb5',
    messagingSenderId: '701125455472',
    projectId: 'dynamic-5a626',
    storageBucket: 'dynamic-5a626.appspot.com',
    iosBundleId: 'com.example.dynamicLinks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA6mhroqAcSc_ihGWtnAuOXHOi9KQXf4s',
    appId: '1:701125455472:ios:abc4687648313945f10eb5',
    messagingSenderId: '701125455472',
    projectId: 'dynamic-5a626',
    storageBucket: 'dynamic-5a626.appspot.com',
    iosBundleId: 'com.example.dynamicLinks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWJuPNsxpi7ikoGLQn5L20_am8AQmeLKE',
    appId: '1:701125455472:web:4f7e8145d49d19aaf10eb5',
    messagingSenderId: '701125455472',
    projectId: 'dynamic-5a626',
    authDomain: 'dynamic-5a626.firebaseapp.com',
    storageBucket: 'dynamic-5a626.appspot.com',
    measurementId: 'G-BMQBFQX8BG',
  );
}
